Fix compile error in GHC 9.2
arowM/heterocephalus pull request #33
Opened 2022-07-11 01:51 UTC by clintonmead

The ConP constructor takes an extra argument in GHC-9.2, and this fix ensures that Heterocephalus compiles for GHC-9.2 whilst continuing to be backwards compatible with pre GHC-9.2. Note that this patch does not introduce logic to handle the new GHC-9.2 syntax (whatever that is), it just ensures that the current behaviour pre GHC-9.2 features can continue to compile under GHC-9.2.

2022-07-11 01:52 UTC, clintonmead commented
This relates to issue: https://github.com/arowM/heterocephalus/issues/32 

I'm not sure how to link this to the issue in Github though sorry.

2022-07-11 08:57 UTC, arowM requested changes
Thanks for the polite PR. It's super helpfull.🎉

Basically it looks good to me, but in some cases, it seems not to be compiled.
I've added a file named `stack-lts-lower.yaml` to the master branch, so rebase it in your branch and make sure that the command `stack test --stack-lts ./stack-lts-lower.yaml` suceeds.

2022-07-11 08:57 UTC, arowM commented on src/Text/Heterocephalus.hs
> +  return (conP (mkConName con) patterns, concat scopes)
It seems template-haskell-compat-v0208 version 0.17 only support `conp`, but not `conP`.
Could you use CPP pragma to handle older versions like [this](https://github.com/arowM/heterocephalus/blob/master/src/Text/Heterocephalus.hs#L74-L81)?

2022-07-12 02:03 UTC, clintonmead commented
I've instead gone to `template-haskell-compat-v0208` version 0.19, becuase `conp` is deprecated in 0.19 and I would prefer to avoid using functions that are deprecated.

I've added an `extra-deps` clause for `template-haskell-compat-v0208` version 0.19 as it's not in `lts-18.28`. 

However this approach is just a matter of taste so feel free to modify this to use the deprecated versions and/or add in CPP. 

Thanks also for your prompt responses and your work on the package!

2022-07-12 02:36 UTC, arowM commented
Thanks.🌸
I'll release a new version after adding backword compatibility for GHC 8.10.

2022-07-12 02:36 UTC, merged